version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.workers.max=2 -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false"
      TERM: dumb

commands:
  restore_gradle_wrapper:
    description: "Restores Gradle Wrapper from cache"
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  restore_gradle_cache:
    description: "Restores Gradle Cache from cache"
    steps:
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "checks/build.gradle.kts" }}
  save_gradle_wrapper:
    description: "Save Gradle Wrapper to cache"
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  save_gradle_cache:
    description: "Save Gradle Cache to cache"
    steps:
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "checks/build.gradle.kts" }}

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - restore_gradle_wrapper
      - restore_gradle_cache
      - run: ./gradlew check
      - save_gradle_wrapper
      - save_gradle_cache
      - store_test_results:
          path: checks/build/test-results/test
      - store_artifacts:
          path: checks/build/reports
          when: always
